### ISSUE TITLE
Unit tests 57 & 58 fail in IE 11

### ISSUE THREAD

**Issue by mikebolt** [tweenjs/tween.js#440]
Custom group.update() doesn't conflict with global TWEEN group (1, 0, 1)
1.Object doesn't support property or method 'assign'TypeError: Object doesn't support property or method 'assign'
   at tests.Custom group.update() doesn't conflict with global TWEEN group (file:///F:/repo/tween.js/test/unit/tests.js:1276:5)
   at Anonymous function (file:///F:/repo/tween.js/test/unit/nodeunit.js:1910:13)
   at Anonymous function (file:///F:/repo/tween.js/test/unit/nodeunit.js:1910:13)
   at exports.runTest (file:///F:/repo/tween.js/test/unit/nodeunit.js:1744:9)
   at Anonymous function (file:///F:/repo/tween.js/test/unit/nodeunit.js:1792:17)
   at Anonymous function (file:///F:/repo/tween.js/test/unit/nodeunit.js:1011:13)
   at iterate (file:///F:/repo/tween.js/test/unit/nodeunit.js:621:13)
   at Anonymous function (file:///F:/repo/tween.js/test/unit/nodeunit.js:632:25)
   at Anonymous function (file:///F:/repo/tween.js/test/unit/nodeunit.js:1013:17)
   at Anonymous function (file:///F:/repo/tween.js/test/unit/nodeunit.js:1632:17)

58.Global TWEEN.update() doesn't conflict with custom group (1, 0, 1)
1.Object doesn't support property or method 'assign'TypeError: Object doesn't support property or method 'assign'
   at tests.Global TWEEN.update() doesn't conflict with custom group (file:///F:/repo/tween.js/test/unit/tests.js:1302:5)
   at Anonymous function (file:///F:/repo/tween.js/test/unit/nodeunit.js:1910:13)
   at Anonymous function (file:///F:/repo/tween.js/test/unit/nodeunit.js:1910:13)
   at exports.runTest (file:///F:/repo/tween.js/test/unit/nodeunit.js:1744:9)
   at Anonymous function (file:///F:/repo/tween.js/test/unit/nodeunit.js:1792:17)
   at Anonymous function (file:///F:/repo/tween.js/test/unit/nodeunit.js:1011:13)
   at iterate (file:///F:/repo/tween.js/test/unit/nodeunit.js:621:13)
   at Anonymous function (file:///F:/repo/tween.js/test/unit/nodeunit.js:632:25)
   at Anonymous function (file:///F:/repo/tween.js/test/unit/nodeunit.js:1013:17)
   at Anonymous function (file:///F:/repo/tween.js/test/unit/nodeunit.js:1632:17)

**Comment by mikebolt** [comment]
Fixed in #449
